#Server
server:
  port: 8181
#JPA
spring:
  datasource:
    url: jdbc:h2:mem:test-db
    username: usr
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect